// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Log struct {
	ID        string `json:"id"`
	SystemID  string `json:"system_id"`
	Level     string `json:"level"`
	Status    string `json:"status"`
	Message   string `json:"message"`
	Timestamp string `json:"timestamp"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterLog struct {
	SystemID  string `json:"system_id"`
	Level     string `json:"level"`
	Status    string `json:"status"`
	Message   string `json:"message"`
	Timestamp string `json:"timestamp"`
}

type RegisterSystem struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Version     string `json:"version"`
}

type System struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Version     string `json:"version"`
	Logs        []*Log `json:"logs"`
}
