DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS systems;

CREATE TABLE systems (
	 id VARCHAR(36) UNIQUE NOT NULL PRIMARY KEY,
	 name VARCHAR(50) NOT NULL,
	 description VARCHAR(200) NOT NULL,
	 version VARCHAR(15) NOT NULL
);

CREATE TABLE logs (
	id VARCHAR(36) UNIQUE NOT NULL PRIMARY KEY,
	system_id VARCHAR(36) NOT NULL REFERENCES systems (id),
	level VARCHAR(30) NOT NULL,
	status VARCHAR(30) NOT NULL,
	message VARCHAR NOT NULL,
	time_stamp TIMESTAMP NOT NULL
);
