name: Golang Tests

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get up postgres
        run: docker compose -f deployments/database/postgresql/docker-compose.yaml up -d
      - name: Get up rabbitmq 
        run: docker compose -f deployments/messaging/rabbitmq/docker-compose.yaml up -d
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Run tests
        run: go test -v ./...
